title: Ambrissh S Raghav
logo: /assets/IMG_8846.png
description: Hey! I am Ambrissh , a second year BS-MS undergrad at IISER Berhampur .
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
